# Generated by Django 5.1.6 on 2025-03-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotroca', '0002_alter_usuario_nome_completo_livro_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
